#!/bin/bash

# Since gcc-4.8, preprocessing includes <stdc-predef.h> automatically,
# invoke cpp without "-C" option makes sure C comments be removed, with
# "-traditional" option, "//" is not treated as comment so that Fortran
# string concatenation expressions are not broken.

CPP=/usr/bin/cpp-4.9

argc=1
argv=("-traditional")

for arg in "$@"
do
    [ "$arg" = "-C" ] && continue
    [ "$arg" = "-traditional" ] && continue
    argv[$argc]="$arg"
    let argc=argc+1
done

exec "$CPP" "${argv[@]}"
